spring:
  application:
    name: hello-admin-server

server:
  port: 8084
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health","info"]

eureka:
  client:
    serviceUrl:
      deaultZone: http://localhost:8761/eureka/