spring:
  application:
    name: community-admin

server:
  port: 8084
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health","info"]

eureka:
  client:
    service-url:
      deault-zone: http://192.168.43.175:8761/eureka/,http://192.168.43.175:8861/eureka/,http://192.168.43.175:8961/eureka/