spring:
  application:
    name: community-zuul
  
server:
  port: 8769
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.43.175:8761/eureka/,http://192.168.43.175:8861/eureka/,http://192.168.43.175:8961/eureka/
zuul:
  routes:
    api-a:
      path: 
      serviceId: 
    
