spring:
  application:
    name: community-eureka-server
server:
  port: 8761
eureka:
  instance:
    hostname: 192.168.43.175
  client:
    registerWithEureka: true   #若部署为集群，应当为true
    fetchRegistry: true        #若部署为集群，应当为true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/,http://${eureka.instance.hostname}:8861/eureka/,http://${eureka.instance.hostname}:8961/eureka/
