spring:
  application:
    name: community-admin

server:
  port: 8084
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health","info"]

eureka:
  client:
    serviceUrl:
      deafultZone: http://localhost:8761/eureka/